name: Update Satellite GeoJSON

on:
  schedule:
    - cron: "0 * * * *"    # Run every hour
  workflow_dispatch:        # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Needed so we can force push safely

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate grouped GeoJSONs
        run: python generate_all_geojson.py

      - name: Commit & Force Push GeoJSON updates
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # add all updated geojson files
          git add output/*.geojson

          # commit only if changes detected
          git commit -m "Auto update grouped GeoJSON" || echo "No changes"

          # sync with remote to avoid push rejection error
          git fetch --all
          git reset --hard origin/main

          # force push to ensure updates
          git push --force
